# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Beam_Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 501, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 10, 181, 101))
        self.groupBox_7.setObjectName("groupBox_7")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_9.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_13.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_14.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_15.setGeometry(QtCore.QRect(110, 20, 82, 17))
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_16.setGeometry(QtCore.QRect(110, 40, 82, 17))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_17.setGeometry(QtCore.QRect(110, 60, 82, 17))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_18.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.radioButton_18.setObjectName("radioButton_18")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_3)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 130, 251, 321))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.hexagonGeometryBox_12 = QtWidgets.QGroupBox(self.page)
        self.hexagonGeometryBox_12.setGeometry(QtCore.QRect(20, 20, 211, 81))
        self.hexagonGeometryBox_12.setObjectName("hexagonGeometryBox_12")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.hexagonGeometryBox_12)
        self.lineEdit_24.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_24 = QtWidgets.QLabel(self.hexagonGeometryBox_12)
        self.label_24.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_24.setObjectName("label_24")
        self.comboBox_24 = QtWidgets.QComboBox(self.hexagonGeometryBox_12)
        self.comboBox_24.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.uChannelGeometryBox_10 = QtWidgets.QGroupBox(self.page_3)
        self.uChannelGeometryBox_10.setGeometry(QtCore.QRect(20, 20, 211, 221))
        self.uChannelGeometryBox_10.setObjectName("uChannelGeometryBox_10")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.uChannelGeometryBox_10)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_18 = QtWidgets.QLabel(self.uChannelGeometryBox_10)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.uChannelGeometryBox_10)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_19.setObjectName("label_19")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.uChannelGeometryBox_10)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_20 = QtWidgets.QLabel(self.uChannelGeometryBox_10)
        self.label_20.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.uChannelGeometryBox_10)
        self.label_21.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.uChannelGeometryBox_10)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.uChannelGeometryBox_10)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 190, 113, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.comboBox_18 = QtWidgets.QComboBox(self.uChannelGeometryBox_10)
        self.comboBox_18.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_19 = QtWidgets.QComboBox(self.uChannelGeometryBox_10)
        self.comboBox_19.setGeometry(QtCore.QRect(130, 90, 69, 22))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_20 = QtWidgets.QComboBox(self.uChannelGeometryBox_10)
        self.comboBox_20.setGeometry(QtCore.QRect(130, 140, 69, 22))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_21 = QtWidgets.QComboBox(self.uChannelGeometryBox_10)
        self.comboBox_21.setGeometry(QtCore.QRect(130, 190, 69, 22))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.rectangleGeometryBox_9 = QtWidgets.QGroupBox(self.page_4)
        self.rectangleGeometryBox_9.setGeometry(QtCore.QRect(20, 20, 211, 221))
        self.rectangleGeometryBox_9.setObjectName("rectangleGeometryBox_9")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.rectangleGeometryBox_9)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_14 = QtWidgets.QLabel(self.rectangleGeometryBox_9)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.rectangleGeometryBox_9)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.rectangleGeometryBox_9)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_16 = QtWidgets.QLabel(self.rectangleGeometryBox_9)
        self.label_16.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.rectangleGeometryBox_9)
        self.label_17.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.rectangleGeometryBox_9)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.rectangleGeometryBox_9)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 190, 113, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.comboBox_14 = QtWidgets.QComboBox(self.rectangleGeometryBox_9)
        self.comboBox_14.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_15 = QtWidgets.QComboBox(self.rectangleGeometryBox_9)
        self.comboBox_15.setGeometry(QtCore.QRect(130, 90, 69, 22))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_16 = QtWidgets.QComboBox(self.rectangleGeometryBox_9)
        self.comboBox_16.setGeometry(QtCore.QRect(130, 140, 69, 22))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_17 = QtWidgets.QComboBox(self.rectangleGeometryBox_9)
        self.comboBox_17.setGeometry(QtCore.QRect(130, 190, 69, 22))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.iBeamGeometryBox_8 = QtWidgets.QGroupBox(self.page_5)
        self.iBeamGeometryBox_8.setGeometry(QtCore.QRect(20, 20, 211, 291))
        self.iBeamGeometryBox_8.setObjectName("iBeamGeometryBox_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.iBeamGeometryBox_8)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label = QtWidgets.QLabel(self.iBeamGeometryBox_8)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.iBeamGeometryBox_8)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_10.setObjectName("label_10")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.iBeamGeometryBox_8)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtWidgets.QLabel(self.iBeamGeometryBox_8)
        self.label_11.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.iBeamGeometryBox_8)
        self.label_12.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.iBeamGeometryBox_8)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.iBeamGeometryBox_8)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 190, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.comboBox_9 = QtWidgets.QComboBox(self.iBeamGeometryBox_8)
        self.comboBox_9.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(self.iBeamGeometryBox_8)
        self.comboBox_10.setGeometry(QtCore.QRect(130, 90, 69, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_11 = QtWidgets.QComboBox(self.iBeamGeometryBox_8)
        self.comboBox_11.setGeometry(QtCore.QRect(130, 140, 69, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_12 = QtWidgets.QComboBox(self.iBeamGeometryBox_8)
        self.comboBox_12.setGeometry(QtCore.QRect(130, 190, 69, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.label_13 = QtWidgets.QLabel(self.iBeamGeometryBox_8)
        self.label_13.setGeometry(QtCore.QRect(10, 220, 71, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.iBeamGeometryBox_8)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 240, 113, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.comboBox_13 = QtWidgets.QComboBox(self.iBeamGeometryBox_8)
        self.comboBox_13.setGeometry(QtCore.QRect(130, 240, 69, 22))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.roundGeometryBox_11 = QtWidgets.QGroupBox(self.page_2)
        self.roundGeometryBox_11.setGeometry(QtCore.QRect(20, 20, 211, 131))
        self.roundGeometryBox_11.setObjectName("roundGeometryBox_11")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.roundGeometryBox_11)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_22 = QtWidgets.QLabel(self.roundGeometryBox_11)
        self.label_22.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.roundGeometryBox_11)
        self.label_23.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_23.setObjectName("label_23")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.roundGeometryBox_11)
        self.lineEdit_23.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.comboBox_22 = QtWidgets.QComboBox(self.roundGeometryBox_11)
        self.comboBox_22.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_23 = QtWidgets.QComboBox(self.roundGeometryBox_11)
        self.comboBox_23.setGeometry(QtCore.QRect(130, 90, 69, 22))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.stackedWidget.addWidget(self.page_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 130, 471, 161))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 50, 131, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 90, 133, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 71, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 50, 133, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(250, 30, 101, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 90, 133, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(250, 70, 111, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 130, 133, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 191, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 30, 71, 20))
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(170, 50, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(170, 90, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(390, 50, 69, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(170, 130, 69, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_8.setGeometry(QtCore.QRect(390, 90, 69, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(240, 10, 111, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_7.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_8.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.radioButton_8.setObjectName("radioButton_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(120, 10, 91, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.radioButton_6.setObjectName("radioButton_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(370, 10, 111, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_10.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_11.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_12.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.radioButton_12.setObjectName("radioButton_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 81, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 300, 471, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 71, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_6.setGeometry(QtCore.QRect(30, 40, 131, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_5.setGeometry(QtCore.QRect(170, 40, 69, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(30, 70, 71, 20))
        self.label_8.setObjectName("label_8")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_6.setGeometry(QtCore.QRect(170, 90, 69, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(30, 90, 131, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(270, 20, 71, 20))
        self.label_9.setObjectName("label_9")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_7.setGeometry(QtCore.QRect(390, 40, 69, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(270, 40, 101, 20))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(180, 430, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 529, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.stackedWidget.hide()

        self.radioButton_9.clicked.connect(self.hideRadio)
        self.radioButton_13.clicked.connect(self.hideRadio)
        self.radioButton_14.clicked.connect(self.hideRadio)
        self.radioButton_15.clicked.connect(self.hideRadio)
        self.radioButton_16.clicked.connect(self.hideRadio)
        self.radioButton_17.clicked.connect(self.hideRadio)
        self.radioButton_18.clicked.connect(self.hideRadio)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def hideRadio(self):

        #Hides geometry inputs based on radio button choice

        self.stackedWidget.show()

        if self.radioButton_13.isChecked():
            self.stackedWidget.setCurrentIndex(1)

        if self.radioButton_14.isChecked():
            self.stackedWidget.setCurrentIndex(3)

        if self.radioButton_9.isChecked():
            self.stackedWidget.setCurrentIndex(2)

        if self.radioButton_15.isChecked():
            self.stackedWidget.setCurrentIndex(4)

        if self.radioButton_16.isChecked():
            self.stackedWidget.setCurrentIndex(0)

        if self.radioButton_17.isChecked():
            self.stackedWidget.hide()

        if self.radioButton_18.isChecked():
            self.stackedWidget.hide()            

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Section Shape"))
        self.radioButton_9.setText(_translate("MainWindow", "U-Channel"))
        self.radioButton_13.setText(_translate("MainWindow", "Rectangle"))
        self.radioButton_14.setText(_translate("MainWindow", "I-Beam"))
        self.radioButton_15.setText(_translate("MainWindow", "Round"))
        self.radioButton_16.setText(_translate("MainWindow", "Hexagon"))
        self.radioButton_17.setText(_translate("MainWindow", "T-beam"))
        self.radioButton_18.setText(_translate("MainWindow", "Angle"))
        self.hexagonGeometryBox_12.setTitle(_translate("MainWindow", "Geometry"))
        self.label_24.setText(_translate("MainWindow", "Side Length"))
        self.comboBox_24.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_24.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_24.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_24.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_24.setItemText(4, _translate("MainWindow", "Inches"))
        self.uChannelGeometryBox_10.setTitle(_translate("MainWindow", "Geometry"))
        self.label_18.setText(_translate("MainWindow", "Height"))
        self.label_19.setText(_translate("MainWindow", "Width"))
        self.label_20.setText(_translate("MainWindow", "Flange Width"))
        self.label_21.setText(_translate("MainWindow", "Channel Width"))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_18.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_18.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_18.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_19.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_19.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_19.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_20.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_20.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_20.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_21.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_21.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_21.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_21.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_21.setItemText(4, _translate("MainWindow", "Inches"))
        self.rectangleGeometryBox_9.setTitle(_translate("MainWindow", "Geometry"))
        self.label_14.setText(_translate("MainWindow", "Outside Height"))
        self.label_15.setText(_translate("MainWindow", "Outside Width"))
        self.label_16.setText(_translate("MainWindow", "Inside Width"))
        self.label_17.setText(_translate("MainWindow", "Inside Height"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_14.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_14.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_14.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_15.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_15.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_15.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_16.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_16.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_16.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_17.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_17.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_17.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_17.setItemText(4, _translate("MainWindow", "Inches"))
        self.iBeamGeometryBox_8.setTitle(_translate("MainWindow", "Geometry"))
        self.label.setText(_translate("MainWindow", "Height"))
        self.label_10.setText(_translate("MainWindow", "Width"))
        self.label_11.setText(_translate("MainWindow", "Web Height"))
        self.label_12.setText(_translate("MainWindow", "Flange Width"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_11.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_11.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_12.setItemText(4, _translate("MainWindow", "Inches"))
        self.label_13.setText(_translate("MainWindow", "Web Width"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_13.setItemText(4, _translate("MainWindow", "Inches"))
        self.roundGeometryBox_11.setTitle(_translate("MainWindow", "Geometry"))
        self.label_22.setText(_translate("MainWindow", "Inner Diameter"))
        self.label_23.setText(_translate("MainWindow", "Outer Diameter"))
        self.comboBox_22.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_22.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_22.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_22.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_22.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_23.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_23.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_23.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_23.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_23.setItemText(4, _translate("MainWindow", "Inches"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Section Calculator"))
        self.groupBox.setTitle(_translate("MainWindow", "Manual Inputs"))
        self.label_2.setText(_translate("MainWindow", " Beam Length "))
        self.label_3.setText(_translate("MainWindow", " Young\'s Modulus"))
        self.label_4.setText(_translate("MainWindow", "2nd Moment of Area"))
        self.label_5.setText(_translate("MainWindow", "Distance from load to closest support"))
        self.label_6.setText(_translate("MainWindow", "Load"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Netwons"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Pounds"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "GPa"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Mpsi"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "m^4"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "cm^4"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "mm^4"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "ft^4"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "in^4"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Load Type"))
        self.radioButton_7.setText(_translate("MainWindow", "Point"))
        self.radioButton_8.setText(_translate("MainWindow", "Distributed"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Support 2"))
        self.radioButton_4.setText(_translate("MainWindow", "Fixed"))
        self.radioButton_5.setText(_translate("MainWindow", "Simple"))
        self.radioButton_6.setText(_translate("MainWindow", "Free"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Load Location"))
        self.radioButton_10.setText(_translate("MainWindow", "Centered"))
        self.radioButton_11.setText(_translate("MainWindow", "Uncentered"))
        self.radioButton_12.setText(_translate("MainWindow", "End"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Support 1"))
        self.radioButton.setText(_translate("MainWindow", "Fixed"))
        self.radioButton_2.setText(_translate("MainWindow", "Simple"))
        self.radioButton_3.setText(_translate("MainWindow", "Free"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Analysis"))
        self.label_7.setText(_translate("MainWindow", "Deflection"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Netwons"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Pounds"))
        self.label_8.setText(_translate("MainWindow", "Static stress"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Pascals"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "PSI"))
        self.label_9.setText(_translate("MainWindow", "Moment"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "N-m"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "N-cm"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "N-mm"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "Ft-lb"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "in-lb"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "in-oz"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Deflection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

