# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Beam_Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 501, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 10, 181, 101))
        self.groupBox_7.setObjectName("groupBox_7")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_9.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_13.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_14.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_15.setGeometry(QtCore.QRect(110, 20, 82, 17))
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_16.setGeometry(QtCore.QRect(110, 40, 82, 17))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_17.setGeometry(QtCore.QRect(110, 60, 82, 17))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_18.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.radioButton_18.setObjectName("radioButton_18")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_3)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 130, 251, 321))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.hexagonGeometryBox_12 = QtWidgets.QGroupBox(self.page)
        self.hexagonGeometryBox_12.setGeometry(QtCore.QRect(20, 20, 211, 81))
        self.hexagonGeometryBox_12.setObjectName("hexagonGeometryBox_12")
        self.HexLength = QtWidgets.QLineEdit(self.hexagonGeometryBox_12)
        self.HexLength.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.HexLength.setObjectName("HexLength")
        self.label_24 = QtWidgets.QLabel(self.hexagonGeometryBox_12)
        self.label_24.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_24.setObjectName("label_24")
        self.HexLengthUnit = QtWidgets.QComboBox(self.hexagonGeometryBox_12)
        self.HexLengthUnit.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.HexLengthUnit.setObjectName("HexLengthUnit")
        self.HexLengthUnit.addItem("")
        self.HexLengthUnit.addItem("")
        self.HexLengthUnit.addItem("")
        self.HexLengthUnit.addItem("")
        self.HexLengthUnit.addItem("")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.uChannelGeometryBox_10 = QtWidgets.QGroupBox(self.page_3)
        self.uChannelGeometryBox_10.setGeometry(QtCore.QRect(20, 20, 211, 221))
        self.uChannelGeometryBox_10.setObjectName("uChannelGeometryBox_10")
        self.ChannelHeight = QtWidgets.QLineEdit(self.uChannelGeometryBox_10)
        self.ChannelHeight.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.ChannelHeight.setObjectName("ChannelHeight")
        self.label_18 = QtWidgets.QLabel(self.uChannelGeometryBox_10)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.uChannelGeometryBox_10)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_19.setObjectName("label_19")
        self.ChannelWidth = QtWidgets.QLineEdit(self.uChannelGeometryBox_10)
        self.ChannelWidth.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.ChannelWidth.setObjectName("ChannelWidth")
        self.label_20 = QtWidgets.QLabel(self.uChannelGeometryBox_10)
        self.label_20.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.uChannelGeometryBox_10)
        self.label_21.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_21.setObjectName("label_21")
        self.ChannelChannel = QtWidgets.QLineEdit(self.uChannelGeometryBox_10)
        self.ChannelChannel.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.ChannelChannel.setObjectName("ChannelChannel")
        self.ChannelFlange = QtWidgets.QLineEdit(self.uChannelGeometryBox_10)
        self.ChannelFlange.setGeometry(QtCore.QRect(10, 190, 113, 20))
        self.ChannelFlange.setObjectName("ChannelFlange")
        self.ChannelHeightUnit = QtWidgets.QComboBox(self.uChannelGeometryBox_10)
        self.ChannelHeightUnit.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.ChannelHeightUnit.setObjectName("ChannelHeightUnit")
        self.ChannelHeightUnit.addItem("")
        self.ChannelHeightUnit.addItem("")
        self.ChannelHeightUnit.addItem("")
        self.ChannelHeightUnit.addItem("")
        self.ChannelHeightUnit.addItem("")
        self.ChannelWidthUnit = QtWidgets.QComboBox(self.uChannelGeometryBox_10)
        self.ChannelWidthUnit.setGeometry(QtCore.QRect(130, 90, 69, 22))
        self.ChannelWidthUnit.setObjectName("ChannelWidthUnit")
        self.ChannelWidthUnit.addItem("")
        self.ChannelWidthUnit.addItem("")
        self.ChannelWidthUnit.addItem("")
        self.ChannelWidthUnit.addItem("")
        self.ChannelWidthUnit.addItem("")
        self.ChannelChannelUnit = QtWidgets.QComboBox(self.uChannelGeometryBox_10)
        self.ChannelChannelUnit.setGeometry(QtCore.QRect(130, 140, 69, 22))
        self.ChannelChannelUnit.setObjectName("ChannelChannelUnit")
        self.ChannelChannelUnit.addItem("")
        self.ChannelChannelUnit.addItem("")
        self.ChannelChannelUnit.addItem("")
        self.ChannelChannelUnit.addItem("")
        self.ChannelChannelUnit.addItem("")
        self.ChannelFlangeUnit = QtWidgets.QComboBox(self.uChannelGeometryBox_10)
        self.ChannelFlangeUnit.setGeometry(QtCore.QRect(130, 190, 69, 22))
        self.ChannelFlangeUnit.setObjectName("ChannelFlangeUnit")
        self.ChannelFlangeUnit.addItem("")
        self.ChannelFlangeUnit.addItem("")
        self.ChannelFlangeUnit.addItem("")
        self.ChannelFlangeUnit.addItem("")
        self.ChannelFlangeUnit.addItem("")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.rectangleGeometryBox_9 = QtWidgets.QGroupBox(self.page_4)
        self.rectangleGeometryBox_9.setGeometry(QtCore.QRect(20, 20, 211, 221))
        self.rectangleGeometryBox_9.setObjectName("rectangleGeometryBox_9")
        self.RectangleOutHeight = QtWidgets.QLineEdit(self.rectangleGeometryBox_9)
        self.RectangleOutHeight.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.RectangleOutHeight.setObjectName("RectangleOutHeight")
        self.label_14 = QtWidgets.QLabel(self.rectangleGeometryBox_9)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.rectangleGeometryBox_9)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_15.setObjectName("label_15")
        self.RectangleOutWidth = QtWidgets.QLineEdit(self.rectangleGeometryBox_9)
        self.RectangleOutWidth.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.RectangleOutWidth.setObjectName("RectangleOutWidth")
        self.label_16 = QtWidgets.QLabel(self.rectangleGeometryBox_9)
        self.label_16.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.rectangleGeometryBox_9)
        self.label_17.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_17.setObjectName("label_17")
        self.RectangleInHeight = QtWidgets.QLineEdit(self.rectangleGeometryBox_9)
        self.RectangleInHeight.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.RectangleInHeight.setObjectName("RectangleInHeight")
        self.RectangleInWidth = QtWidgets.QLineEdit(self.rectangleGeometryBox_9)
        self.RectangleInWidth.setGeometry(QtCore.QRect(10, 190, 113, 20))
        self.RectangleInWidth.setObjectName("RectangleInWidth")
        self.RectangleOutHeightUnit = QtWidgets.QComboBox(self.rectangleGeometryBox_9)
        self.RectangleOutHeightUnit.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.RectangleOutHeightUnit.setObjectName("RectangleOutHeightUnit")
        self.RectangleOutHeightUnit.addItem("")
        self.RectangleOutHeightUnit.addItem("")
        self.RectangleOutHeightUnit.addItem("")
        self.RectangleOutHeightUnit.addItem("")
        self.RectangleOutHeightUnit.addItem("")
        self.RectangleOutWidthUnit = QtWidgets.QComboBox(self.rectangleGeometryBox_9)
        self.RectangleOutWidthUnit.setGeometry(QtCore.QRect(130, 90, 69, 22))
        self.RectangleOutWidthUnit.setObjectName("RectangleOutWidthUnit")
        self.RectangleOutWidthUnit.addItem("")
        self.RectangleOutWidthUnit.addItem("")
        self.RectangleOutWidthUnit.addItem("")
        self.RectangleOutWidthUnit.addItem("")
        self.RectangleOutWidthUnit.addItem("")
        self.RectangleInHeightUnit = QtWidgets.QComboBox(self.rectangleGeometryBox_9)
        self.RectangleInHeightUnit.setGeometry(QtCore.QRect(130, 140, 69, 22))
        self.RectangleInHeightUnit.setObjectName("RectangleInHeightUnit")
        self.RectangleInHeightUnit.addItem("")
        self.RectangleInHeightUnit.addItem("")
        self.RectangleInHeightUnit.addItem("")
        self.RectangleInHeightUnit.addItem("")
        self.RectangleInHeightUnit.addItem("")
        self.RectangleInWidthUnit = QtWidgets.QComboBox(self.rectangleGeometryBox_9)
        self.RectangleInWidthUnit.setGeometry(QtCore.QRect(130, 190, 69, 22))
        self.RectangleInWidthUnit.setObjectName("RectangleInWidthUnit")
        self.RectangleInWidthUnit.addItem("")
        self.RectangleInWidthUnit.addItem("")
        self.RectangleInWidthUnit.addItem("")
        self.RectangleInWidthUnit.addItem("")
        self.RectangleInWidthUnit.addItem("")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.iBeamGeometryBox_8 = QtWidgets.QGroupBox(self.page_5)
        self.iBeamGeometryBox_8.setGeometry(QtCore.QRect(20, 20, 211, 291))
        self.iBeamGeometryBox_8.setObjectName("iBeamGeometryBox_8")
        self.iBeamHeight = QtWidgets.QLineEdit(self.iBeamGeometryBox_8)
        self.iBeamHeight.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.iBeamHeight.setObjectName("iBeamHeight")
        self.label = QtWidgets.QLabel(self.iBeamGeometryBox_8)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.iBeamGeometryBox_8)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_10.setObjectName("label_10")
        self.iBeamWidth = QtWidgets.QLineEdit(self.iBeamGeometryBox_8)
        self.iBeamWidth.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.iBeamWidth.setObjectName("iBeamWidth")
        self.label_12 = QtWidgets.QLabel(self.iBeamGeometryBox_8)
        self.label_12.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_12.setObjectName("label_12")
        self.iBeamFlange = QtWidgets.QLineEdit(self.iBeamGeometryBox_8)
        self.iBeamFlange.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.iBeamFlange.setObjectName("iBeamFlange")
        self.iBeamWeb = QtWidgets.QLineEdit(self.iBeamGeometryBox_8)
        self.iBeamWeb.setGeometry(QtCore.QRect(10, 190, 113, 20))
        self.iBeamWeb.setObjectName("iBeamWeb")
        self.iBeamHeightUnit = QtWidgets.QComboBox(self.iBeamGeometryBox_8)
        self.iBeamHeightUnit.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.iBeamHeightUnit.setObjectName("iBeamHeightUnit")
        self.iBeamHeightUnit.addItem("")
        self.iBeamHeightUnit.addItem("")
        self.iBeamHeightUnit.addItem("")
        self.iBeamHeightUnit.addItem("")
        self.iBeamHeightUnit.addItem("")
        self.iBeamWidthUnit = QtWidgets.QComboBox(self.iBeamGeometryBox_8)
        self.iBeamWidthUnit.setGeometry(QtCore.QRect(130, 90, 69, 22))
        self.iBeamWidthUnit.setObjectName("iBeamWidthUnit")
        self.iBeamWidthUnit.addItem("")
        self.iBeamWidthUnit.addItem("")
        self.iBeamWidthUnit.addItem("")
        self.iBeamWidthUnit.addItem("")
        self.iBeamWidthUnit.addItem("")
        self.iBeamFlangeUnit = QtWidgets.QComboBox(self.iBeamGeometryBox_8)
        self.iBeamFlangeUnit.setGeometry(QtCore.QRect(130, 140, 69, 22))
        self.iBeamFlangeUnit.setObjectName("iBeamFlangeUnit")
        self.iBeamFlangeUnit.addItem("")
        self.iBeamFlangeUnit.addItem("")
        self.iBeamFlangeUnit.addItem("")
        self.iBeamFlangeUnit.addItem("")
        self.iBeamFlangeUnit.addItem("")
        self.iBeamWebUnit = QtWidgets.QComboBox(self.iBeamGeometryBox_8)
        self.iBeamWebUnit.setGeometry(QtCore.QRect(130, 190, 69, 22))
        self.iBeamWebUnit.setObjectName("iBeamWebUnit")
        self.iBeamWebUnit.addItem("")
        self.iBeamWebUnit.addItem("")
        self.iBeamWebUnit.addItem("")
        self.iBeamWebUnit.addItem("")
        self.iBeamWebUnit.addItem("")
        self.label_13 = QtWidgets.QLabel(self.iBeamGeometryBox_8)
        self.label_13.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.roundGeometryBox_11 = QtWidgets.QGroupBox(self.page_2)
        self.roundGeometryBox_11.setGeometry(QtCore.QRect(20, 20, 211, 131))
        self.roundGeometryBox_11.setObjectName("roundGeometryBox_11")
        self.outerD = QtWidgets.QLineEdit(self.roundGeometryBox_11)
        self.outerD.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.outerD.setObjectName("outerD")
        self.label_22 = QtWidgets.QLabel(self.roundGeometryBox_11)
        self.label_22.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.roundGeometryBox_11)
        self.label_23.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_23.setObjectName("label_23")
        self.innerD = QtWidgets.QLineEdit(self.roundGeometryBox_11)
        self.innerD.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.innerD.setObjectName("innerD")
        self.outerDUnit = QtWidgets.QComboBox(self.roundGeometryBox_11)
        self.outerDUnit.setGeometry(QtCore.QRect(130, 40, 69, 22))
        self.outerDUnit.setObjectName("outerDUnit")
        self.outerDUnit.addItem("")
        self.outerDUnit.addItem("")
        self.outerDUnit.addItem("")
        self.outerDUnit.addItem("")
        self.outerDUnit.addItem("")
        self.innerDUnit = QtWidgets.QComboBox(self.roundGeometryBox_11)
        self.innerDUnit.setGeometry(QtCore.QRect(130, 90, 69, 22))
        self.innerDUnit.setObjectName("innerDUnit")
        self.innerDUnit.addItem("")
        self.innerDUnit.addItem("")
        self.innerDUnit.addItem("")
        self.innerDUnit.addItem("")
        self.innerDUnit.addItem("")
        self.stackedWidget.addWidget(self.page_2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(260, 10, 221, 161))
        self.groupBox_8.setObjectName("groupBox_8")
        self.sectionAreaUnit = QtWidgets.QComboBox(self.groupBox_8)
        self.sectionAreaUnit.setGeometry(QtCore.QRect(140, 70, 69, 21))
        self.sectionAreaUnit.setObjectName("sectionAreaUnit")
        self.sectionAreaUnit.addItem("")
        self.sectionAreaUnit.addItem("")
        self.sectionAreaUnit.addItem("")
        self.sectionAreaUnit.addItem("")
        self.sectionAreaUnit.addItem("")
        self.sectionArea = QtWidgets.QLineEdit(self.groupBox_8)
        self.sectionArea.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.sectionArea.setReadOnly(True)
        self.sectionArea.setObjectName("sectionArea")
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_8)
        self.label_26.setGeometry(QtCore.QRect(10, 100, 121, 16))
        self.label_26.setObjectName("label_26")
        self.sectionMomentUnit = QtWidgets.QComboBox(self.groupBox_8)
        self.sectionMomentUnit.setGeometry(QtCore.QRect(140, 120, 69, 21))
        self.sectionMomentUnit.setObjectName("sectionMomentUnit")
        self.sectionMomentUnit.addItem("")
        self.sectionMomentUnit.addItem("")
        self.sectionMomentUnit.addItem("")
        self.sectionMomentUnit.addItem("")
        self.sectionMomentUnit.addItem("")
        self.sectionMoment = QtWidgets.QLineEdit(self.groupBox_8)
        self.sectionMoment.setGeometry(QtCore.QRect(10, 120, 113, 20))
        self.sectionMoment.setReadOnly(True)
        self.sectionMoment.setObjectName("sectionMoment")
        self.sectionCalc = QtWidgets.QPushButton(self.groupBox_8)
        self.sectionCalc.setGeometry(QtCore.QRect(70, 20, 75, 23))
        self.sectionCalc.setObjectName("sectionCalc")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 130, 471, 161))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 40, 131, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 80, 133, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 71, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 40, 133, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(250, 20, 101, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 80, 133, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(250, 60, 111, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 120, 133, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 100, 191, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 71, 20))
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(170, 40, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(170, 80, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(390, 40, 69, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(170, 120, 69, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_8.setGeometry(QtCore.QRect(390, 80, 69, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 110, 161, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(240, 10, 111, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_7.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_8.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.radioButton_8.setObjectName("radioButton_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(120, 10, 91, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.radioButton_6.setObjectName("radioButton_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(370, 10, 111, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_10.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_11.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_12.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.radioButton_12.setObjectName("radioButton_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 81, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 300, 471, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 71, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_6.setGeometry(QtCore.QRect(30, 40, 131, 20))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_5.setGeometry(QtCore.QRect(170, 40, 69, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(30, 70, 71, 20))
        self.label_8.setObjectName("label_8")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_6.setGeometry(QtCore.QRect(170, 90, 69, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(30, 90, 131, 20))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(270, 20, 71, 20))
        self.label_9.setObjectName("label_9")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_7.setGeometry(QtCore.QRect(390, 40, 69, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(270, 40, 101, 20))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(180, 430, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.stackedWidget.hide()

        self.radioButton_9.clicked.connect(self.hideRadio)
        self.radioButton_13.clicked.connect(self.hideRadio)
        self.radioButton_14.clicked.connect(self.hideRadio)
        self.radioButton_15.clicked.connect(self.hideRadio)
        self.radioButton_16.clicked.connect(self.hideRadio)
        self.radioButton_17.clicked.connect(self.hideRadio)
        self.radioButton_18.clicked.connect(self.hideRadio)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def calcSection(self):

        

    def hideRadio(self):

        #Hides geometry inputs based on radio button choice

        self.stackedWidget.show()

        if self.radioButton_13.isChecked():
            self.stackedWidget.setCurrentIndex(1)

        if self.radioButton_14.isChecked():
            self.stackedWidget.setCurrentIndex(3)

        if self.radioButton_9.isChecked():
            self.stackedWidget.setCurrentIndex(2)

        if self.radioButton_15.isChecked():
            self.stackedWidget.setCurrentIndex(4)

        if self.radioButton_16.isChecked():
            self.stackedWidget.setCurrentIndex(0)

        if self.radioButton_17.isChecked():
            self.stackedWidget.hide()

        if self.radioButton_18.isChecked():
            self.stackedWidget.hide()                                                
   
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Section Shape"))
        self.radioButton_9.setText(_translate("MainWindow", "U-Channel"))
        self.radioButton_13.setText(_translate("MainWindow", "Rectangle"))
        self.radioButton_14.setText(_translate("MainWindow", "I-Beam"))
        self.radioButton_15.setText(_translate("MainWindow", "Round"))
        self.radioButton_16.setText(_translate("MainWindow", "Hexagon"))
        self.radioButton_17.setText(_translate("MainWindow", "T-beam"))
        self.radioButton_18.setText(_translate("MainWindow", "Angle"))
        self.hexagonGeometryBox_12.setTitle(_translate("MainWindow", "Geometry"))
        self.label_24.setText(_translate("MainWindow", "Side Length"))
        self.HexLengthUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.HexLengthUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.HexLengthUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.HexLengthUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.HexLengthUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.uChannelGeometryBox_10.setTitle(_translate("MainWindow", "Geometry"))
        self.label_18.setText(_translate("MainWindow", "Height"))
        self.label_19.setText(_translate("MainWindow", "Width"))
        self.label_20.setText(_translate("MainWindow", "Flange Width"))
        self.label_21.setText(_translate("MainWindow", "Channel Width"))
        self.ChannelHeightUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.ChannelHeightUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.ChannelHeightUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.ChannelHeightUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.ChannelHeightUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.ChannelWidthUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.ChannelWidthUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.ChannelWidthUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.ChannelWidthUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.ChannelWidthUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.ChannelChannelUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.ChannelChannelUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.ChannelChannelUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.ChannelChannelUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.ChannelChannelUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.ChannelFlangeUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.ChannelFlangeUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.ChannelFlangeUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.ChannelFlangeUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.ChannelFlangeUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.rectangleGeometryBox_9.setTitle(_translate("MainWindow", "Geometry"))
        self.label_14.setText(_translate("MainWindow", "Outside Height"))
        self.label_15.setText(_translate("MainWindow", "Outside Width"))
        self.label_16.setText(_translate("MainWindow", "Inside Width"))
        self.label_17.setText(_translate("MainWindow", "Inside Height"))
        self.RectangleOutHeightUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.RectangleOutHeightUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.RectangleOutHeightUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.RectangleOutHeightUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.RectangleOutHeightUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.RectangleOutWidthUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.RectangleOutWidthUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.RectangleOutWidthUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.RectangleOutWidthUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.RectangleOutWidthUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.RectangleInHeightUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.RectangleInHeightUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.RectangleInHeightUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.RectangleInHeightUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.RectangleInHeightUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.RectangleInWidthUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.RectangleInWidthUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.RectangleInWidthUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.RectangleInWidthUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.RectangleInWidthUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.iBeamGeometryBox_8.setTitle(_translate("MainWindow", "Geometry"))
        self.label.setText(_translate("MainWindow", "Height"))
        self.label_10.setText(_translate("MainWindow", "Flange Width"))
        self.label_12.setText(_translate("MainWindow", "Flange Thickness"))
        self.iBeamHeightUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.iBeamHeightUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.iBeamHeightUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.iBeamHeightUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.iBeamHeightUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.iBeamWidthUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.iBeamWidthUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.iBeamWidthUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.iBeamWidthUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.iBeamWidthUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.iBeamFlangeUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.iBeamFlangeUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.iBeamFlangeUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.iBeamFlangeUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.iBeamFlangeUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.iBeamWebUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.iBeamWebUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.iBeamWebUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.iBeamWebUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.iBeamWebUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.label_13.setText(_translate("MainWindow", "Web Width"))
        self.roundGeometryBox_11.setTitle(_translate("MainWindow", "Geometry"))
        self.label_22.setText(_translate("MainWindow", "Inner Diameter"))
        self.label_23.setText(_translate("MainWindow", "Outer Diameter"))
        self.outerDUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.outerDUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.outerDUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.outerDUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.outerDUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.innerDUnit.setItemText(0, _translate("MainWindow", "Meters"))
        self.innerDUnit.setItemText(1, _translate("MainWindow", "cm"))
        self.innerDUnit.setItemText(2, _translate("MainWindow", "mm"))
        self.innerDUnit.setItemText(3, _translate("MainWindow", "Feet"))
        self.innerDUnit.setItemText(4, _translate("MainWindow", "Inches"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Outputs"))
        self.sectionAreaUnit.setItemText(0, _translate("MainWindow", "m^2"))
        self.sectionAreaUnit.setItemText(1, _translate("MainWindow", "cm^2"))
        self.sectionAreaUnit.setItemText(2, _translate("MainWindow", "mm^2"))
        self.sectionAreaUnit.setItemText(3, _translate("MainWindow", "ft^2"))
        self.sectionAreaUnit.setItemText(4, _translate("MainWindow", "in^2"))
        self.label_25.setText(_translate("MainWindow", "Area"))
        self.label_26.setText(_translate("MainWindow", "Second Moment of Area"))
        self.sectionMomentUnit.setItemText(0, _translate("MainWindow", "m^4"))
        self.sectionMomentUnit.setItemText(1, _translate("MainWindow", "cm^4"))
        self.sectionMomentUnit.setItemText(2, _translate("MainWindow", "mm^4"))
        self.sectionMomentUnit.setItemText(3, _translate("MainWindow", "ft^4"))
        self.sectionMomentUnit.setItemText(4, _translate("MainWindow", "in^4"))
        self.sectionCalc.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Section Calculator"))
        self.groupBox.setTitle(_translate("MainWindow", "Manual Inputs"))
        self.label_2.setText(_translate("MainWindow", " Beam Length "))
        self.label_3.setText(_translate("MainWindow", " Young\'s Modulus"))
        self.label_4.setText(_translate("MainWindow", "2nd Moment of Area"))
        self.label_5.setText(_translate("MainWindow", "Distance from load to closest support"))
        self.label_6.setText(_translate("MainWindow", "Load"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Netwons"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Pounds"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "GPa"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Mpsi"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Meters"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "cm"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Feet"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Inches"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "m^4"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "cm^4"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "mm^4"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "ft^4"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "in^4"))
        self.pushButton_2.setText(_translate("MainWindow", "Import From Section Calculator"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Load Type"))
        self.radioButton_7.setText(_translate("MainWindow", "Point"))
        self.radioButton_8.setText(_translate("MainWindow", "Distributed"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Support 2"))
        self.radioButton_4.setText(_translate("MainWindow", "Fixed"))
        self.radioButton_5.setText(_translate("MainWindow", "Simple"))
        self.radioButton_6.setText(_translate("MainWindow", "Free"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Load Location"))
        self.radioButton_10.setText(_translate("MainWindow", "Centered"))
        self.radioButton_11.setText(_translate("MainWindow", "Uncentered"))
        self.radioButton_12.setText(_translate("MainWindow", "End"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Support 1"))
        self.radioButton.setText(_translate("MainWindow", "Fixed"))
        self.radioButton_2.setText(_translate("MainWindow", "Simple"))
        self.radioButton_3.setText(_translate("MainWindow", "Free"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Analysis"))
        self.label_7.setText(_translate("MainWindow", "Deflection"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Netwons"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Pounds"))
        self.label_8.setText(_translate("MainWindow", "Static stress"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Pascals"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "PSI"))
        self.label_9.setText(_translate("MainWindow", "Moment"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "N-m"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "N-cm"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "N-mm"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "Ft-lb"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "in-lb"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "in-oz"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Deflection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

